'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SRS_Project

    Partial Public Class ACTIVITYLOG
        Public Property ACTIVITYID As Integer
        Public Property LOGDATETIME As Date
        Public Property NRIC As String
        Public Property DESCRIPTION As String
    
    End Class

End Namespace
