'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SRS_Project

    Partial Public Class COMPANY
        Public Property COMPANYID As String
        Public Property COMPANYNAME As String
        Public Property ADDRESSLINE1 As String
        Public Property ADDRESSLINE2 As String
        Public Property ADDRESSLINE3 As String
        Public Property TELNO As String
        Public Property FAXNO As String
        Public Property COMPANYLOGOPATH As String
        Public Property COMPANYHEADERPATH As String
        Public Property HOMEPAGEHEADERPATH As String
        Public Property DEFAULTLANGUAGE As String
        Public Property STARTEDON As Date
        Public Property DAYTOLOCKREASON As Integer
        Public Property ISINUSED As Boolean
    
    End Class

End Namespace
