'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SRS_Project

    Partial Public Class FEEDBACK
        Public Property FEEDBACKID As Integer
        Public Property NRIC As String
        Public Property CONTENT As String
        Public Property ISREPLIED As Boolean
        Public Property REPLIEDBY As String
        Public Property REPLIEDON As Date
    
    End Class

End Namespace
