'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SRS_Project

    Partial Public Class HYPERLINK
        Public Property COMPANYID As String
        Public Property HYPERLINKID As Integer
        Public Property TITLE As String
        Public Property URL As String
        Public Property CREATEDBY As String
        Public Property CREATEDON As Date
        Public Property UPDATEDBY As String
        Public Property UPDATEDON As Date
    
    End Class

End Namespace
