'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace SRS_Project

    Partial Public Class SRSdbEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=SRSdbEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property ACTIVITYLOGs() As DbSet(Of ACTIVITYLOG)
        Public Overridable Property ANNOUNCEMENTs() As DbSet(Of ANNOUNCEMENT)
        Public Overridable Property ATTENDACNESTATUSVALIDATIONs() As DbSet(Of ATTENDACNESTATUSVALIDATION)
        Public Overridable Property ATTENDANCESTATUS() As DbSet(Of ATTENDANCESTATU)
        Public Overridable Property COMPANies() As DbSet(Of COMPANY)
        Public Overridable Property DEPARTMENTs() As DbSet(Of DEPARTMENT)
        Public Overridable Property FEEDBACKs() As DbSet(Of FEEDBACK)
        Public Overridable Property HOLIDAYs() As DbSet(Of HOLIDAY)
        Public Overridable Property HYPERLINKs() As DbSet(Of HYPERLINK)
        Public Overridable Property PERSONALMESSAGEs() As DbSet(Of PERSONALMESSAGE)
        Public Overridable Property POORATTENDANCEREASONs() As DbSet(Of POORATTENDANCEREASON)
        Public Overridable Property SHIFTs() As DbSet(Of SHIFT)
        Public Overridable Property SHIFTSCHEDULEs() As DbSet(Of SHIFTSCHEDULE)
        Public Overridable Property STAFFs() As DbSet(Of STAFF)
        Public Overridable Property STAFFGROUPs() As DbSet(Of STAFFGROUP)
        Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
        Public Overridable Property USERSSHIFTs() As DbSet(Of USERSSHIFT)
    
    End Class

End Namespace
