'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SRS_Project

    Partial Public Class USERSSHIFT
        Public Property COMPANYID As String
        Public Property USERSHIFID As Integer
        Public Property NRIC As String
        Public Property SHIFTID As String
        Public Property EFFECTIVEON As Date
    
    End Class

End Namespace
