'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace mTime

    Partial Public Class ATTENDACNESTATUSVALIDATION
        Public Property ASVID As Integer
        Public Property ATTENDANCEDATE As Date
        Public Property ATTENDANCESTATUS As String
        Public Property TIMEIN As Nullable(Of Date)
        Public Property TIMEOUT As Nullable(Of Date)
        Public Property LATEINREASONID As String
        Public Property LATEINDESCRIPTION As String
        Public Property EARLYOUTREASONID As String
        Public Property EARLYOUTDESCRIPTION As String
        Public Property SUBMITTEDBY As String
        Public Property SUBMITTEDON As Date
        Public Property VALIDATIONSTATUS As String
        Public Property VALIDATEDBY As String
        Public Property VALIDATEDON As Nullable(Of Date)
    
    End Class

End Namespace
