'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace mTime

    Partial Public Class EXDBTRANSSYNCTRDATA
        Public Property TRID As Integer
        Public Property CTRLNAME As String
        Public Property DOORPOINTNAME As String
        Public Property TRDATETIME As Date
        Public Property TRSTATUS As String
        Public Property CARDNO As String
        Public Property STAFFNO As String
        Public Property NRIC As String
        Public Property DATA As String
        Public Property EXDATA As String
        Public Property LOGDATETIME As String
        Public Property RETRIEVEDON As Date
    
    End Class

End Namespace
