'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace mTime

    Partial Public Class HOLIDAY
        Public Property HOLIDAYID As Integer
        Public Property HOLIDAYNAME As String
        Public Property FROM As Date
        Public Property [UNTIL] As Date
        Public Property ISINUSED As Boolean
        Public Property CREATEDBY As String
        Public Property CREATEDON As Date
        Public Property UPDATEDBY As String
        Public Property UPDATEDON As Nullable(Of Date)
    
    End Class

End Namespace
