'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace mTime

    Partial Public Class PERSONALMESSAGE
        Public Property PERSONALMESSAGEID As Integer
        Public Property NRIC As String
        Public Property ABOUT As String
        Public Property CONTENT As String
        Public Property ISREAD As Boolean
        Public Property READON As Nullable(Of Date)
        Public Property ISDELETED As Boolean
        Public Property DELETEBY As String
        Public Property DELETEON As Nullable(Of Date)
    
    End Class

End Namespace
