'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace mTime

    Partial Public Class SHIFT
        Public Property SHIFTID As String
        Public Property FLEXISTARTTIMEFROM1 As Date
        Public Property FLEXISTARTTIMETO1 As Date
        Public Property WORKHOUR1 As Integer
        Public Property ISOFFDAY1 As Boolean
        Public Property FLEXISTARTTIMEFROM2 As Date
        Public Property FLEXISTARTTIMETO2 As Date
        Public Property WORKHOUR2 As Integer
        Public Property ISOFFDAY2 As Boolean
        Public Property FLEXISTARTTIMEFROM3 As Date
        Public Property FLEXISTARTTIMETO3 As Date
        Public Property WORKHOUR3 As Integer
        Public Property ISOFFDAY3 As Boolean
        Public Property FLEXISTARTTIMEFROM4 As Date
        Public Property FLEXISTARTTIMETO4 As Date
        Public Property WORKHOUR4 As Integer
        Public Property ISOFFDAY4 As Boolean
        Public Property FLEXISTARTTIMEFROM5 As Date
        Public Property FLEXISTARTTIMETO5 As Date
        Public Property WORKHOUR5 As Integer
        Public Property ISOFFDAY5 As Boolean
        Public Property FLEXISTARTTIMEFROM6 As Date
        Public Property FLEXISTARTTIMETO6 As Date
        Public Property WORKHOUR6 As Integer
        Public Property ISOFFDAY6 As Boolean
        Public Property FLEXISTARTTIMEFROM7 As Date
        Public Property FLEXISTARTTIMETO7 As Date
        Public Property WORKHOUR7 As Integer
        Public Property ISOFFDAY7 As Boolean
        Public Property GRACEPERIODFORLATEIN As Integer
        Public Property GRACEPERIODFOREARLYOUT As Integer
        Public Property REMARK As String
        Public Property ISINUSED As Boolean
        Public Property CREATEDBY As String
        Public Property CREATEDON As Date
        Public Property UPDATEDBY As String
        Public Property UPDATEDON As Nullable(Of Date)
    
    End Class

End Namespace
