'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace mTime

    Partial Public Class STAFF
        Public Property NRIC As String
        Public Property STAFFNO As String
        Public Property FIRSTNAME As String
        Public Property LASTNAME As String
        Public Property USERGROUPID As String
        Public Property GENDER As String
        Public Property GRADE As String
        Public Property CONTACTNO1 As String
        Public Property CONTACTNO2 As String
        Public Property ADDRESS As String
        Public Property EMAIL As String
        Public Property DEPARTMENTID As String
        Public Property STATUS As String
        Public Property PASSWORD As String
        Public Property CREATEDBY As String
        Public Property CREATEDON As Date
        Public Property UPDATEDBY As String
        Public Property UPDATEDON As Nullable(Of Date)
    
    End Class

End Namespace
